src/main/php/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::pattern( 'facility_id', '[0-9]+' );
Route::pattern( 'patient_id', '[0-9]+' );
Route::pattern( 'tech_support_message_id', '[0-9]+' );
Route::pattern( 'days', '[0-9]{1,2}' );
Route::pattern( 'week', '[0-9]{1,2}' );
Route::pattern( 'log_week', '[0-9]{1,2}' );

Route::group( array( 'middleware' => [ 'guest' ] ), function () {

	Route::get( '/', array( 'as' => 'login', 'uses' => 'AuthController@index' ) );

	Route::get( 'login/byToken', array( 'as' => 'login-by-token', 'uses' => 'AuthController@loginByTokenHandler' ) );

	Route::post( '/login', array( 'as' => 'login-handler', 'uses' => 'AuthController@loginHandler' ) );

    Route::get( 'fitbit-steps-mismatch-get', array(
        'as'   => 'fitbit-steps-mismatch-get',
        'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchGet'
    ) );

} );

Route::get( 'logout', array( 'as' => 'logout', 'uses' => 'AuthController@logout' ) );

Route::group( array( 'middleware' => [ 'auth', 'auth.token', 'user-permission' ] ), function () {

	Route::get( '/dashboard', array( 'as' => 'dashboard', 'uses' => 'HomeController@index' ) );

    Route::get('errorlog', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get( 'cacheremove', 'CacheServiceController@clearAllCacheKey');

	Route::get( 'facilities', array( 'as' => 'facilities.list', 'uses' => 'HomeController@facilityList' ) );

	Route::get( 'facility/{facility_id}/providers', array( 'as' => 'facility.providers', 'uses' => 'HomeController@facilityProviders' ) );

	Route::get( 'facility/{facility_id}/patients', array( 'as' => 'facility.patients', 'uses' => 'HomeController@facilityPatients' ) );

	Route::any( 'facility/{facility_id}/manage', [ 'as' => 'facility.setting', 'uses' => 'HomeController@facilitySetting' ] );

	Route::get( 'patient/{patient_id}/detail/{facility_id?}', array( 'as' => 'patient.detail', 'uses' => 'HomeController@patientDetail' ) );

	Route::get( 'patient/{patient_id}/messages/{user_id?}', array(
		'as'   => 'patient.user.messages',
		'uses' => 'HomeController@patientUserMessages'
	) );

	Route::get( 'patient/{patient_id}/activities', array(
		'as'   => 'patient.activity.log',
		'uses' => 'HomeController@patientLogs'
	) );
	Route::get( 'patient/{patient_id}/debug-info', array(
		'as'   => 'patient.debug-info',
		'uses' => 'HomeController@patientDebugInfo'
	) );

	Route::get( 'search-patient', array(
		'as'   => 'search.patient',
		'uses' => 'HomeController@searchPatient'
	) );

	Route::get( 'patient/import', array(
		'as'   => 'patient.import',
		'uses' => 'HomeController@patientImport'
	) );
	Route::post( 'patient/enrol', array(
		'as'   => 'patient.enrol',
		'uses' => 'HomeController@patientEnrollment'
	) );

	Route::get( 'manage-report-schedule', array(
		'as'   => 'manage-schedule',
		'uses' => 'ReportSchedule@manageReportSchedule'
	) );

    Route::get( 'fitbit-steps', array(
        'as'   => 'fitbit-steps',
        'uses' => 'ReportController@sendMessages'
    ) );

	Route::get( 'support/tickets', array(
		'as'   => 'support.tickets',
		'uses' => 'SupportController@viewTickets'
	) );

    Route::any( 'cache-email', array(
        'as'   => 'cache-email',
        'uses' => 'CommonController@cacheEmail'
    ) );

	Route::group( array( 'as' => 'report.', 'prefix' => 'report', 'middleware' => [ 'cache-service' ] ), function () {
		Route::get( 'facility-reports/{facility_id?}', [
			'as'   => 'facility-reports',
			'uses' => 'ReportController@facilityReports'
		] );
		Route::get( 'users/active/{facility_id}/{days?}', [
			'as'   => 'facility.users.active',
			'uses' => 'ReportController@activeUsers'
		] );
		Route::get( 'users/entries/{facility_id}/{days?}', [
			'as'   => 'facility.users.entries',
			'uses' => 'ReportController@userEntries'
		] );
		Route::get( 'users/registration/{facility_id}/{days?}', [
			'as'   => 'facility.users.registration',
			'uses' => 'ReportController@userRegistrations'
		] );
		Route::get( 'misfit/steps/{facility_id}/{days?}', [
			'as'   => 'facility.misfit.steps',
			'uses' => 'ReportController@userMisfitSteps'
		] );
		Route::get( 'misfit/never-active/{facility_id}', [
			'as'   => 'facility.misfit.never.active',
			'uses' => 'ReportController@userMisfitNeverActive'
		] );
		Route::get( 'facility/messages/{facility_id}', [
			'as'   => 'facility.messages',
			'uses' => 'ReportController@facilityMessages'
		] );
		Route::get( 'video-calls/{facility_id}/{days?}', [
			'as'   => 'facility.video.calls',
			'uses' => 'ReportController@facilityVideoCalls'
		] );
		Route::get( 'users/lead-coach/{facility_id}', [
			'as'   => 'facility.users.leadCoach',
			'uses' => 'ReportController@facilityUsersLeadCoach'
		] );
		Route::get( 'facility/patient-preferences/{facility_id}', [
			'as'   => 'facility.patient-preferences',
			'uses' => 'ReportController@facilityPatientPreferences'
		] );
		Route::get( 'curriculum/activity/{facility_id}', [
			'as'   => 'facility.curriculum.activity',
			'uses' => 'ReportController@facilityCurriculumActivity'
		] );
		Route::get( 'facility/coach-patients/{facility_id}', [
			'as'   => 'coach.patients',
			'uses' => 'ReportController@facilityCoaches'
		] );
		Route::get( 'facility/weekly-participation/{facility_id}', [
			'as'   => 'weekly.participation',
			'uses' => 'ReportController@weeklyParticipation'
		] );
		Route::get( 'facility/sessions-completed/{facility_id}', [
			'as'   => 'sessions.completed',
			'uses' => 'ReportController@sessionsCompletedReport'
		] );
        Route::get( 'facility/self-register/{facility_id}', [
            'as'   => 'self.register',
            'uses' => 'ReportController@selfRegisterReport'
        ] );
        Route::get( 'facility/registration/{facility_id}', [
            'as'   => 'user.registration',
            'uses' => 'ReportController@usersRegistration'
        ] );
        Route::get( 'facility/import-patient', [
            'as'   => 'import.patient',
            'uses' => 'ReportController@importPatient'
        ] );
		Route::get( 'facility/engagement/{facility_id}', [
			'as'   => 'engagement',
			'uses' => 'ReportController@engagementReport'
		] );
		Route::get( 'facility/coach-engagement/{facility_id}', [
			'as'   => 'coach.engagement',
			'uses' => 'ReportController@coachEngagementReport'
		] );
		Route::get( 'facility/week-cohort/{facility_id}', [
			'as'   => 'week-cohort',
			'uses' => 'ReportController@weekCohortReport'
		] );

        Route::get( 'facility/fitbit-steps-mismatch', array(
            'as'   => 'fitbit-steps-mismatch',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReport'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-detail', array(
            'as'   => 'fitbit-steps-mismatch-detail',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetail'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-details', array(
            'as'   => 'fitbit-steps-mismatch-details',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetails'
        ) );

        Route::get( 'facility/week-cohort', [
            'as'   => 'week-cohort-all-facility',
            'uses' => 'CommonController@weekCohortReport'
        ] );

		Route::get( 'facility/week-cohort/{facility_id}/group/{week?}/{coach?}', [
			'as'   => 'week-cohort-patients',
			'uses' => 'ReportController@weekCohortPatients'
		] );
		Route::get( 'facility/week-cohort/{facility_id}/group/{week}/detail/{log_week}', [
			'as'   => 'week-cohort-patients-log',
			'uses' => 'ReportController@weekCohortPatientsLog'
		] );
		Route::get( 'facility/patient-fitbit-activity/{facility_id}', [
			'as'   => 'patient.fitbit.activity',
			'uses' => 'ReportController@patientFitbitActivity'
		] );
		Route::get( 'facility/patient-fitbit-weight/{facility_id}/{days?}', [
			'as'   => 'patient.fitbit.weight',
			'uses' => 'ReportController@patientFitbitWeightReport'
		] );
		Route::get( 'facility/missing-patient-provider/{facility_id}', [
			'as'   => 'missing.patient-provider',
			'uses' => 'ReportController@missingPatientProviderMapping'
		] );

		Route::get( 'facility/member-coach-list/{facility_id}', [
			'as'   => 'facility.member-coach-list',
			'uses' => 'ReportController@memberCoachesListReport'
		] );

		Route::get( 'facility/shipping-addresses/{facility_id}', [
			'as'   => 'facility.shipping-addresses',
			'uses' => 'ReportController@facilityShippingAddresses'
		] );

		Route::get( 'provider/{provider_id}/patient-interaction/{week?}', [
			'as'   => 'coach.patient-interaction',
			'uses' => 'ReportController@coachPatientInteraction'
		] );


		Route::get( 'enrollment/{days?}', [
			'as'   => 'enrollment',
			'uses' => 'ReportController@enrollmentReport'
		] );
		Route::get( 'missing-fitbit-logs/activity/{days?}', [
			'as'   => 'missing-fitbit-log.activity',
			'uses' => 'ReportController@missingFitbitActivityLog'
		] );
		Route::get( 'missing-fitbit-logs/weight/{days?}', [
			'as'   => 'missing-fitbit-log.weight',
			'uses' => 'ReportController@missingFitbitWeightLog'
		] );

		Route::get( 'coach-weekly-participation', array(
			'as'   => 'coach-weekly-participation',
			'uses' => 'ProviderController@providerWeeklyParticipationReport'
		) );

		Route::get( 'feedback-messages', [
			'as'   => 'feedbackMessages',
			'uses' => 'ReportController@feedbackMessages'
		] );
		Route::get( 'patient-without-lead-coach', [
			'as'   => 'noLeadCoachOneonOne',
			'uses' => 'ReportController@patientWithoutLeadCoachOneOnOne'
		] );

		Route::get( 'messages/unreplied', [
			'as'   => 'unRepliedMessages',
			'uses' => 'ReportController@unRepliedMessages'

src/main/php/app/Models/Provider.php
<?php

namespace HealthSlateAdmin\Models;

use Illuminate\Database\Eloquent\Model;

class Provider extends Model {

	protected $table = 'provider';

	protected $primaryKey = 'provider_id';

	public $timestamps = false;

	public function facility() {
		return $this->hasOne( 'HealthSlateAdmin\Models\Facility', 'facility_id', 'facility_id' );
	}

	public function patients() {
		return $this->belongsToMany( 'HealthSlateAdmin\Models\Patient', 'provider_patient', 'providers_provider_id', 'patients_patient_id');
	}

	/**
	 * belongsToMany relation for fetching counts only
	 * @return mixed
	 */
	public function patientCountRelation() {
		return $this->belongsToMany( 'HealthSlateAdmin\Models\Patient', 'provider_patient', 'providers_provider_id', 'patients_patient_id')
			->select($this->getConnection()->raw('count(*) as aggregate'))->groupBy('providers_provider_id');
	}

	/**
	 * get patient count for a provider
	 * @return int
	 */
	public function getPatientCountAttribute() {
		if ( ! array_key_exists('patientCountRelation', $this->relations)) $this->load('patientCountRelation');

		$related = $this->getRelation('patientCountRelation')->first();
		return ($related) ? $related->aggregate : 0;
	}

	public function user() {
		return $this->belongsTo( 'HealthSlateAdmin\Models\User', 'user_id', 'user_id' );
	}

	// coach has many notes for a patient
	public function coachNotes() {
		return $this->hasMany( 'HealthSlateAdmin\Models\CoachNote', 'provider_id' ,'provider_id');
	}

	public function oneToOneSessions() {
		return $this->hasMany( 'HealthSlateAdmin\Models\OneToOneSession', 'provider_id', 'provider_id' );
	}

}

src/main/php/app/Models/User.php
<?php

namespace HealthSlateAdmin\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model {

	protected $table = 'users';

	protected $primaryKey = 'user_id';

	public $timestamps = false;

	protected $fillable = array('email', 'first_name', 'last_name');

	public function getFullNameAttribute() {
		return $this->first_name . ' ' . $this->last_name;
	}

	public function getAddressInfoAttribute() {
		return $this->address . ' ' . $this->city. ' ' . $this->state;
	}

	public function scopeIsRegistrationCompleted( $query, $is_registration_completed = true ){
		if($is_registration_completed){
			// registered 1
			return $query->whereRaw($this->getConnection()->raw('ORD(is_registration_completed) = 1'));
		}else{
			// not yet registered (null,0)
			return $query->whereRaw($this->getConnection()->raw('( (is_registration_completed IS NULL) OR ORD(is_registration_completed) = 0 )'));
		}
	}

	public function authority() {
		return $this->hasOne( 'HealthSlateAdmin\Models\UserRole', 'user_id', 'user_id' )->whereNotNull('user_id');
	}

	public function appAccessLogs() {
		return $this->hasMany( 'HealthSlateAdmin\Models\AppAccessLog', 'user_id' ,'user_id');
	}

	public function coachGoalAssessments() {
		return $this->hasMany( 'HealthSlateAdmin\Models\CoachGoalAssessment', 'user_id' ,'user_id');
	}

	public function emailNotificationMessages() {
		return $this->hasMany( 'HealthSlateAdmin\Models\EmailNotificationMessage', 'user_id' ,'user_id');
	}

	// Here in this table user_id is for provider
	public function messages() {
		return $this->hasMany( 'HealthSlateAdmin\Models\Message', 'user_id' ,'user_id');
	}

	// a user will have either patient or provider
	public function patient() {
		return $this->hasOne( 'HealthSlateAdmin\Models\Patient', 'user_id', 'user_id' )->whereNotNull('user_id');
	}

	// a user will have either patient or provider
	public function provider() {
		return $this->hasOne( 'HealthSlateAdmin\Models\Provider', 'user_id', 'user_id' );
	}

	// hasOne care_giver ?
	// hasMany log.
	// hasMany server_log?
}

src/main/php/app/Http/Controllers/ProviderController.php
<?php

namespace HealthSlateAdmin\Http\Controllers;

use HealthSlateAdmin\Http\Controllers\Controller;
use HealthSlateAdmin\Models\User;
use Validator;

class ProviderController extends Controller {
	/**
	 *  common variable for passing data to view
	 * @var array
	 */
	protected $data = array();

	/**
	 * @var User
	 */
	protected $user;

	/**
	 * @param User $user
	 */
	function __construct( User $user ) {
		$this->user = $user;
	}

	/**
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function providerWeeklyParticipationReport() {
		$this->data['css'] = [ 'datetime' ];
		$this->data['js']  = [ 'datetime' ];

		$this->data['show_duration_filter'] = true;
		$this->data['report_src']           = route( 'ajax.report.coach-weekly-participation' );

		$this->data['report_meta'] = (object) [
			'title'      => 'Weekly Participation Report',
			'body_class' => 'weekly-participation coach-weekly-participation'

		];

		return view( 'report.provider.my-weekly-participation', $this->data );
	}

	/**
	 * @param Validator $validator
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function ajaxProviderWeeklyParticipationReport( Validator $validator ) {
		$provider = $this->user->where( 'email', '=', session( 'user' )->userName )->first()->provider()->first();
		// is user is not a $provider?
		if ( empty( $provider ) ) {
			return response()->json( [ 'error' => 'Coach provider not found' ] );
		}
		info( 'Processing Request for ProviderController@ajaxProviderWeeklyParticipationReport ' );
		request()->merge( [ 'coach' => $provider->provider_id, '_patient_hyperlink' => true ] );

		return app( 'HealthSlateAdmin\Http\Controllers\ReportingServiceAjaxController' )->weeklyParticipationReport( $validator, $provider->facility_id );
	}

}

src/main/php/resources/views/provider/provider-patients.blade.php
@extends('includes.admin-layout')

@section('page-title')
    {{ (! empty( $provider->user ) ? $provider->user->full_name.' - Patients' : '') }}
@stop

@section('body-class')
    provider-patients-report
@stop

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="{{route('dashboard')}}"><span class="glyphicon glyphicon-home"></span> Dashboard</a></li>
        <li><a href="{{route('report.facility-reports',['facility_id' => $provider->facility->facility_id])}}"><span class="glyphicon glyphicon-list-alt"></span> Facility Reports</a></li>
        <li><a href="{{route('report.coach.patients',['facility_id' => $provider->facility->facility_id ])}}"><span class="glyphicon glyphicon-list-alt"></span> {{ $provider->facility->name }} - Coach List</a></li>
        <li class="active">{{ (! empty( $provider->user ) ? $provider->user->full_name.' - Patients' : '') }}</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header hide">
                    <h3 class="box-title">&nbsp;</h3>

                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="hs-dt-filter well margin-b-20">
                        <h4>Filters</h4>
                        {!! Form::open( array('method' => 'get', 'class' => 'filter-form', 'role' => 'form') ) !!}

                        <div class="form-group">
                            Recent Weeks
                            {!! Form::select('week', ['0' => 'Any', '1' => '1', '2' => '2', '3' => '3','5' => '5'], request('week',0), [
                            'class' => 'form-control trigger-dt-change',
                            'data-toggle' => 'tooltip', 'title' => 'Filter by weeks'
                            ]) !!}
                        </div>
                        {!! Form::close() !!}
                        <div class="clearfix"></div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover hs-table" data-src="{{ route('ajax.report.coach.patient-interaction',['provider_id' => $provider->provider_id ]) }}">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>MRN</th>
                                <th class="text-center">
                                    Last Active
                                    <span data-container="body" data-toggle="tooltip" title="Days since last activity of patient" class="text-blue glyphicon glyphicon-info-sign"></span>
                                </th>
                                <th class="text-center">
                                    # of Messages Received
                                    <span data-container="body" data-toggle="tooltip" title="No. of Messages Received from {{ (! empty( $provider->user ) ? $provider->user->full_name : 'provider') }}" class="text-blue glyphicon glyphicon-info-sign"></span>
                                </th>
                                <th class="text-center">
                                    # of Messages Sent
                                    <span data-container="body" data-toggle="tooltip" title="No. of Messages Sent to {{ (! empty( $provider->user ) ? $provider->user->full_name : 'provider') }}" class="text-blue glyphicon glyphicon-info-sign"></span>
                                </th>
                                <th class="text-center">
                                    # of 1:1 calls
                                    <span data-container="body" data-toggle="tooltip" title="One 2 One Sessions" class="text-blue glyphicon glyphicon-info-sign"></span>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="7" class="text-center"> {{ trans('common.table_loading_records') }} </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->


                <div class="box-footer">
                    <blockquote>
                        <p class="text-muted text-sm">{!! trans('common.note_deleted_patient_excluded') !!}</p>
                    </blockquote>
                </div>
            </div>
            <!-- /.box -->
        </div>
    </div>

@stop