src/main/php/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::pattern( 'facility_id', '[0-9]+' );
Route::pattern( 'patient_id', '[0-9]+' );
Route::pattern( 'tech_support_message_id', '[0-9]+' );
Route::pattern( 'days', '[0-9]{1,2}' );
Route::pattern( 'week', '[0-9]{1,2}' );
Route::pattern( 'log_week', '[0-9]{1,2}' );

Route::group( array( 'middleware' => [ 'guest' ] ), function () {

	Route::get( '/', array( 'as' => 'login', 'uses' => 'AuthController@index' ) );

	Route::get( 'login/byToken', array( 'as' => 'login-by-token', 'uses' => 'AuthController@loginByTokenHandler' ) );

	Route::post( '/login', array( 'as' => 'login-handler', 'uses' => 'AuthController@loginHandler' ) );

    Route::get( 'fitbit-steps-mismatch-get', array(
        'as'   => 'fitbit-steps-mismatch-get',
        'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchGet'
    ) );

} );

Route::get( 'logout', array( 'as' => 'logout', 'uses' => 'AuthController@logout' ) );

Route::group( array( 'middleware' => [ 'auth', 'auth.token', 'user-permission' ] ), function () {

	Route::get( '/dashboard', array( 'as' => 'dashboard', 'uses' => 'HomeController@index' ) );

    Route::get('errorlog', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get( 'cacheremove', 'CacheServiceController@clearAllCacheKey');

	Route::get( 'facilities', array( 'as' => 'facilities.list', 'uses' => 'HomeController@facilityList' ) );

	Route::get( 'facility/{facility_id}/providers', array( 'as' => 'facility.providers', 'uses' => 'HomeController@facilityProviders' ) );

	Route::get( 'facility/{facility_id}/patients', array( 'as' => 'facility.patients', 'uses' => 'HomeController@facilityPatients' ) );

	Route::any( 'facility/{facility_id}/manage', [ 'as' => 'facility.setting', 'uses' => 'HomeController@facilitySetting' ] );

	Route::get( 'patient/{patient_id}/detail/{facility_id?}', array( 'as' => 'patient.detail', 'uses' => 'HomeController@patientDetail' ) );

	Route::get( 'patient/{patient_id}/messages/{user_id?}', array(
		'as'   => 'patient.user.messages',
		'uses' => 'HomeController@patientUserMessages'
	) );

	Route::get( 'patient/{patient_id}/activities', array(
		'as'   => 'patient.activity.log',
		'uses' => 'HomeController@patientLogs'
	) );
	Route::get( 'patient/{patient_id}/debug-info', array(
		'as'   => 'patient.debug-info',
		'uses' => 'HomeController@patientDebugInfo'
	) );

	Route::get( 'search-patient', array(
		'as'   => 'search.patient',
		'uses' => 'HomeController@searchPatient'
	) );

	Route::get( 'patient/import', array(
		'as'   => 'patient.import',
		'uses' => 'HomeController@patientImport'
	) );
	Route::post( 'patient/enrol', array(
		'as'   => 'patient.enrol',
		'uses' => 'HomeController@patientEnrollment'
	) );

	Route::get( 'manage-report-schedule', array(
		'as'   => 'manage-schedule',
		'uses' => 'ReportSchedule@manageReportSchedule'
	) );

    Route::get( 'fitbit-steps', array(
        'as'   => 'fitbit-steps',
        'uses' => 'ReportController@sendMessages'
    ) );

	Route::get( 'support/tickets', array(
		'as'   => 'support.tickets',
		'uses' => 'SupportController@viewTickets'
	) );

    Route::any( 'cache-email', array(
        'as'   => 'cache-email',
        'uses' => 'CommonController@cacheEmail'
    ) );

	Route::group( array( 'as' => 'report.', 'prefix' => 'report', 'middleware' => [ 'cache-service' ] ), function () {
		Route::get( 'facility-reports/{facility_id?}', [
			'as'   => 'facility-reports',
			'uses' => 'ReportController@facilityReports'
		] );
		Route::get( 'users/active/{facility_id}/{days?}', [
			'as'   => 'facility.users.active',
			'uses' => 'ReportController@activeUsers'
		] );
		Route::get( 'users/entries/{facility_id}/{days?}', [
			'as'   => 'facility.users.entries',
			'uses' => 'ReportController@userEntries'
		] );
		Route::get( 'users/registration/{facility_id}/{days?}', [
			'as'   => 'facility.users.registration',
			'uses' => 'ReportController@userRegistrations'
		] );
		Route::get( 'misfit/steps/{facility_id}/{days?}', [
			'as'   => 'facility.misfit.steps',
			'uses' => 'ReportController@userMisfitSteps'
		] );
		Route::get( 'misfit/never-active/{facility_id}', [
			'as'   => 'facility.misfit.never.active',
			'uses' => 'ReportController@userMisfitNeverActive'
		] );
		Route::get( 'facility/messages/{facility_id}', [
			'as'   => 'facility.messages',
			'uses' => 'ReportController@facilityMessages'
		] );
		Route::get( 'video-calls/{facility_id}/{days?}', [
			'as'   => 'facility.video.calls',
			'uses' => 'ReportController@facilityVideoCalls'
		] );
		Route::get( 'users/lead-coach/{facility_id}', [
			'as'   => 'facility.users.leadCoach',
			'uses' => 'ReportController@facilityUsersLeadCoach'
		] );
		Route::get( 'facility/patient-preferences/{facility_id}', [
			'as'   => 'facility.patient-preferences',
			'uses' => 'ReportController@facilityPatientPreferences'
		] );
		Route::get( 'curriculum/activity/{facility_id}', [
			'as'   => 'facility.curriculum.activity',
			'uses' => 'ReportController@facilityCurriculumActivity'
		] );
		Route::get( 'facility/coach-patients/{facility_id}', [
			'as'   => 'coach.patients',
			'uses' => 'ReportController@facilityCoaches'
		] );
		Route::get( 'facility/weekly-participation/{facility_id}', [
			'as'   => 'weekly.participation',
			'uses' => 'ReportController@weeklyParticipation'
		] );
		Route::get( 'facility/sessions-completed/{facility_id}', [
			'as'   => 'sessions.completed',
			'uses' => 'ReportController@sessionsCompletedReport'
		] );
        Route::get( 'facility/self-register/{facility_id}', [
            'as'   => 'self.register',
            'uses' => 'ReportController@selfRegisterReport'
        ] );
        Route::get( 'facility/registration/{facility_id}', [
            'as'   => 'user.registration',
            'uses' => 'ReportController@usersRegistration'
        ] );
        Route::get( 'facility/import-patient', [
            'as'   => 'import.patient',
            'uses' => 'ReportController@importPatient'
        ] );
		Route::get( 'facility/engagement/{facility_id}', [
			'as'   => 'engagement',
			'uses' => 'ReportController@engagementReport'
		] );
		Route::get( 'facility/coach-engagement/{facility_id}', [
			'as'   => 'coach.engagement',
			'uses' => 'ReportController@coachEngagementReport'
		] );
		Route::get( 'facility/week-cohort/{facility_id}', [
			'as'   => 'week-cohort',
			'uses' => 'ReportController@weekCohortReport'
		] );

        Route::get( 'facility/fitbit-steps-mismatch', array(
            'as'   => 'fitbit-steps-mismatch',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReport'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-detail', array(
            'as'   => 'fitbit-steps-mismatch-detail',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetail'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-details', array(
            'as'   => 'fitbit-steps-mismatch-details',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetails'
        ) );

        Route::get( 'facility/week-cohort', [
            'as'   => 'week-cohort-all-facility',
            'uses' => 'CommonController@weekCohortReport'
        ] );

		Route::get( 'facility/week-cohort/{facility_id}/group/{week?}/{coach?}', [
			'as'   => 'week-cohort-patients',
			'uses' => 'ReportController@weekCohortPatients'
		] );
		Route::get( 'facility/week-cohort/{facility_id}/group/{week}/detail/{log_week}', [
			'as'   => 'week-cohort-patients-log',
			'uses' => 'ReportController@weekCohortPatientsLog'
		] );
		Route::get( 'facility/patient-fitbit-activity/{facility_id}', [
			'as'   => 'patient.fitbit.activity',
			'uses' => 'ReportController@patientFitbitActivity'
		] );
		Route::get( 'facility/patient-fitbit-weight/{facility_id}/{days?}', [
			'as'   => 'patient.fitbit.weight',
			'uses' => 'ReportController@patientFitbitWeightReport'
		] );
		Route::get( 'facility/missing-patient-provider/{facility_id}', [
			'as'   => 'missing.patient-provider',
			'uses' => 'ReportController@missingPatientProviderMapping'
		] );

		Route::get( 'facility/member-coach-list/{facility_id}', [
			'as'   => 'facility.member-coach-list',
			'uses' => 'ReportController@memberCoachesListReport'
		] );

		Route::get( 'facility/shipping-addresses/{facility_id}', [
			'as'   => 'facility.shipping-addresses',
			'uses' => 'ReportController@facilityShippingAddresses'
		] );

		Route::get( 'provider/{provider_id}/patient-interaction/{week?}', [
			'as'   => 'coach.patient-interaction',
			'uses' => 'ReportController@coachPatientInteraction'
		] );


		Route::get( 'enrollment/{days?}', [
			'as'   => 'enrollment',
			'uses' => 'ReportController@enrollmentReport'
		] );
		Route::get( 'missing-fitbit-logs/activity/{days?}', [
			'as'   => 'missing-fitbit-log.activity',
			'uses' => 'ReportController@missingFitbitActivityLog'
		] );
		Route::get( 'missing-fitbit-logs/weight/{days?}', [
			'as'   => 'missing-fitbit-log.weight',
			'uses' => 'ReportController@missingFitbitWeightLog'
		] );

		Route::get( 'coach-weekly-participation', array(
			'as'   => 'coach-weekly-participation',
			'uses' => 'ProviderController@providerWeeklyParticipationReport'
		) );

		Route::get( 'feedback-messages', [
			'as'   => 'feedbackMessages',
			'uses' => 'ReportController@feedbackMessages'
		] );
		Route::get( 'patient-without-lead-coach', [
			'as'   => 'noLeadCoachOneonOne',
			'uses' => 'ReportController@patientWithoutLeadCoachOneOnOne'
		] );

		Route::get( 'messages/unreplied', [
			'as'   => 'unRepliedMessages',
			'uses' => 'ReportController@unRepliedMessages'

src/main/php/app/Models/Message.php
<?php

namespace HealthSlateAdmin\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Message extends Model {

	protected $table = 'message';
	protected $primaryKey = 'message_id';
	public $timestamps = false;

	// user_id is storing provider's user_id.
	public function providerUser() {
		return $this->belongsTo( 'HealthSlateAdmin\Models\User', 'user_id', 'user_id' );
	}

	public function getIsSentAttribute() {
		return ($this->owner == 'PATIENT') ? true : false;
	}

	public function getSentOnAttribute() {
		if(empty($this->timestamp)){
			return "";
		}
		return Carbon::createFromTimestamp($this->timestamp/1000)->format('M, d Y h:i A');
	}

	public function getReadedAttribute() {
		return (ord($this->read_status)) ? true : false;
	}

	public function patient() {
		return $this->belongsTo( 'HealthSlateAdmin\Models\Patient', 'patient_id', 'patient_id' );
	}
}

src/main/php/app/Models/User.php
<?php

namespace HealthSlateAdmin\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model {

	protected $table = 'users';

	protected $primaryKey = 'user_id';

	public $timestamps = false;

	protected $fillable = array('email', 'first_name', 'last_name');

	public function getFullNameAttribute() {
		return $this->first_name . ' ' . $this->last_name;
	}

	public function getAddressInfoAttribute() {
		return $this->address . ' ' . $this->city. ' ' . $this->state;
	}

	public function scopeIsRegistrationCompleted( $query, $is_registration_completed = true ){
		if($is_registration_completed){
			// registered 1
			return $query->whereRaw($this->getConnection()->raw('ORD(is_registration_completed) = 1'));
		}else{
			// not yet registered (null,0)
			return $query->whereRaw($this->getConnection()->raw('( (is_registration_completed IS NULL) OR ORD(is_registration_completed) = 0 )'));
		}
	}

	public function authority() {
		return $this->hasOne( 'HealthSlateAdmin\Models\UserRole', 'user_id', 'user_id' )->whereNotNull('user_id');
	}

	public function appAccessLogs() {
		return $this->hasMany( 'HealthSlateAdmin\Models\AppAccessLog', 'user_id' ,'user_id');
	}

	public function coachGoalAssessments() {
		return $this->hasMany( 'HealthSlateAdmin\Models\CoachGoalAssessment', 'user_id' ,'user_id');
	}

	public function emailNotificationMessages() {
		return $this->hasMany( 'HealthSlateAdmin\Models\EmailNotificationMessage', 'user_id' ,'user_id');
	}

	// Here in this table user_id is for provider
	public function messages() {
		return $this->hasMany( 'HealthSlateAdmin\Models\Message', 'user_id' ,'user_id');
	}

	// a user will have either patient or provider
	public function patient() {
		return $this->hasOne( 'HealthSlateAdmin\Models\Patient', 'user_id', 'user_id' )->whereNotNull('user_id');
	}

	// a user will have either patient or provider
	public function provider() {
		return $this->hasOne( 'HealthSlateAdmin\Models\Provider', 'user_id', 'user_id' );
	}

	// hasOne care_giver ?
	// hasMany log.
	// hasMany server_log?
}

src/main/php/resources/views/blocks/chat-message-div.blade.php
<?php
/**
 * User: spatel
 * Date: 14/1/16
 */
?>
<div class="direct-chat-msg @if(!$message->is_sent) right @endif" data-message-id="{{$message->message_id}}">
    <div class="direct-chat-info clearfix">
        <span class="direct-chat-name @if($message->is_sent) pull-left @else pull-right @endif">@if($message->is_sent) {{ $patient->user->full_name }}  @else {{ @$message->providerUser->full_name }}@endif</span>
        <span class="direct-chat-timestamp  @if($message->is_sent) pull-right @else pull-left @endif">{{ $message->sent_on}}</span>
    </div>
    <!-- /.direct-chat-info -->
    <img class="direct-chat-img" src="@if($message->is_sent){{ !empty($patient->image_path) ? config('healthslate.profile_image_base_url').$patient->image_path : '' }} @else {{ '' }}@endif" alt="Message User Image" onerror="this.src=document.querySelector('.parameters [name=alt_image_url]').value;this.onerror='';"/><!-- /.direct-chat-img -->
    <div class="direct-chat-text">
        <div class="html-text">{!! strip_tags($message->message, config('healthslate.allowed_html_tags')) !!}</div>
        @if(!empty($message->image_path))
            <img src="{{ config('healthslate.message_image_base_url').$message->image_path }}" class="sm-image" onerror="this.src=document.querySelector('.parameters [name=alt_image_url]').value;this.onerror='';"/>
        @endif
        @if($message->readed)
            <small class="pull-right" data-toggle="tooltip" title="Read Status" data-container="body">
                <i class="glyphicon glyphicon-ok font-small"></i>
                <i class="glyphicon glyphicon-ok font-small"></i>
            </small>@endif
    </div>
    <!-- /.direct-chat-text -->
</div>
<!--/.direct-chat-messages-->

src/main/php/resources/views/blocks/chat-user-li.blade.php
<?php
/**
 * User: spatel
 * Date: 14/1/16
 */
?>
<li>
    <div class="{{ !empty($message->providerUser) ? 'redirect-to pointer' : '' }}" data-href="{{route('patient.user.messages',['patient_id' => $patient->patient_id ,'user_id' => @$message->providerUser->user_id])}}">
        <img class="contacts-list-img" src="{{ asset('img/default-user-100x100.png') }}">

        <div class="contacts-list-info">
            <span class="contacts-list-name">
              {{ !empty($message->providerUser) ? $message->providerUser->full_name : '' }}&nbsp;
                <small class="contacts-list-date pull-right">{{ $message->sent_on}}</small>
            </span>
            <span class="contacts-list-msg">
                <span class="html-text">{!! str_limit(strip_tags($message->message, config('healthslate.allowed_html_tags')), 30) !!}</span>
                @if($message->readed)
                    <small class="pull-right" data-toggle="tooltip" title="Read Status" data-container="body">
                        <i class="glyphicon glyphicon-ok font-small text-green"></i>
                        <i class="glyphicon glyphicon-ok font-small text-green"></i>
                    </small>
                @endif
            </span>
        </div>
        <!-- /.contacts-list-info -->
    </div>
</li><!-- End Contact Item -->

src/main/php/resources/views/blocks/patient-log-timeline-div.blade.php
<?php
/**
 * User: spatel
 * Date: 18/1/16
 */
?>
<!-- The time line -->
<ul class="timeline">
    @forelse($log_group as $day => $logs)
        <!-- timeline time label -->
        <li class="time-label">
            <span class="bg-light-blue">
            {{ $day }}
            </span>
        </li>
        <!-- /.timeline-label -->

        <!-- timeline item -->
        <li>
            <i class="glyphicon glyphicon-info-sign bg-green"></i>
            <div class="timeline-item">
                <div class="timeline-body">
                    @foreach($logs->reverse() as $log)
                        <div class="log-block">
                            <a class="btn btn-app {{ strtolower($log->log_type) }} @if(strtolower($log->log_type) == 'meal'){{ $log->is_processed ? "bg-light-green" : "bg-light-gray" }}@elseif(strtolower($log->log_type) == 'weight') bg-light-gray @else bg-light-green @endif">
                                <p>
                                    @if(strtolower($log->log_type) == 'meal')
                                        @if($log->is_processed)
                                        @if($patient->diabetes_type_id == $HS_CONSTANTS->TYPE_2_DIABETES_TYPE_ID)
                                            {{ (!empty($log->foodLogSummary) ? format_weight($log->foodLogSummary->carbs, 1).'g' : "" ) }}
                                            <br/>
                                            Carbs
                                        @elseif($patient->diabetes_type_id == $HS_CONSTANTS->DPP_FAT_DIABETES_TYPE_ID)
                                            {{ (!empty($log->foodLogSummary) ? format_weight($log->foodLogSummary->fats, 1).'g' : "" ) }}
                                            <br/>
                                            Fat
                                        @elseif($patient->diabetes_type_id == $HS_CONSTANTS->DPP_CAL_DIABETES_TYPE_ID)
                                            {{ (!empty($log->foodLogSummary) ? format_weight($log->foodLogSummary->calories, 1).'g' : "" ) }}
                                            <br/>
                                            Calories
                                        @endif
                                        @else
                                            <br/><small>In Progress</small>
                                        @endif
                                        <i class="glyphicon glyphicon-apple text-green log-icon"></i>
                                    @elseif(strtolower($log->log_type) == 'medication')
                                        Took <br/>Med
                                    @elseif(strtolower($log->log_type) == 'glucose')
                                        {{ !empty($log->glucoseLog) ? $log->glucoseLog->glucose_level : "&nbsp;" }} <br/>mg/dl
                                    @elseif(strtolower($log->log_type) == 'activityminute')
                                        {{ !empty($log->activityLog) ? $log->activityLog->minutes_performed : "&nbsp;" }} <br/> mins
                                    @elseif(strtolower($log->log_type) == 'weight')
                                        {{ !empty($log->miscLog) ? format_weight($log->miscLog->weight) : "&nbsp;" }} <br/> lbs
                                    @else
                                        {{ ($log->log_type) }}
                                    @endif
                                </p>
                                <p class="hide">{{ $log->log_type }}</p>
                                <span>{{ $log->log_time_only }}</span>
                            </a>
                                <span class="log-text">
                                    @if(strtolower($log->log_type) == 'meal')
                                        {{ !empty($log->foodLogSummary) ? $log->foodLogSummary->type : "&nbsp;" }}
                                    @elseif(strtolower($log->log_type) == 'activityminute')
                                        Activity
                                    @else
                                        {{ $log->log_type }}
                                    @endif
                                </span>
                        </div>
                    @endforeach
                </div>
            </div>
        </li>
        <!-- END timeline item -->

    @empty
        <li>
            <div class="timeline-item">
                <div class="timeline-body">
                    No Recent Logs Found
                </div>
            </div>
        </li>
    @endforelse

</ul>