src/main/php/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::pattern( 'facility_id', '[0-9]+' );
Route::pattern( 'patient_id', '[0-9]+' );
Route::pattern( 'tech_support_message_id', '[0-9]+' );
Route::pattern( 'days', '[0-9]{1,2}' );
Route::pattern( 'week', '[0-9]{1,2}' );
Route::pattern( 'log_week', '[0-9]{1,2}' );

Route::group( array( 'middleware' => [ 'guest' ] ), function () {

	Route::get( '/', array( 'as' => 'login', 'uses' => 'AuthController@index' ) );

	Route::get( 'login/byToken', array( 'as' => 'login-by-token', 'uses' => 'AuthController@loginByTokenHandler' ) );

	Route::post( '/login', array( 'as' => 'login-handler', 'uses' => 'AuthController@loginHandler' ) );

    Route::get( 'fitbit-steps-mismatch-get', array(
        'as'   => 'fitbit-steps-mismatch-get',
        'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchGet'
    ) );

} );

Route::get( 'logout', array( 'as' => 'logout', 'uses' => 'AuthController@logout' ) );

Route::group( array( 'middleware' => [ 'auth', 'auth.token', 'user-permission' ] ), function () {

	Route::get( '/dashboard', array( 'as' => 'dashboard', 'uses' => 'HomeController@index' ) );

    Route::get('errorlog', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get( 'cacheremove', 'CacheServiceController@clearAllCacheKey');

	Route::get( 'facilities', array( 'as' => 'facilities.list', 'uses' => 'HomeController@facilityList' ) );

	Route::get( 'facility/{facility_id}/providers', array( 'as' => 'facility.providers', 'uses' => 'HomeController@facilityProviders' ) );

	Route::get( 'facility/{facility_id}/patients', array( 'as' => 'facility.patients', 'uses' => 'HomeController@facilityPatients' ) );

	Route::any( 'facility/{facility_id}/manage', [ 'as' => 'facility.setting', 'uses' => 'HomeController@facilitySetting' ] );

	Route::get( 'patient/{patient_id}/detail/{facility_id?}', array( 'as' => 'patient.detail', 'uses' => 'HomeController@patientDetail' ) );

	Route::get( 'patient/{patient_id}/messages/{user_id?}', array(
		'as'   => 'patient.user.messages',
		'uses' => 'HomeController@patientUserMessages'
	) );

	Route::get( 'patient/{patient_id}/activities', array(
		'as'   => 'patient.activity.log',
		'uses' => 'HomeController@patientLogs'
	) );
	Route::get( 'patient/{patient_id}/debug-info', array(
		'as'   => 'patient.debug-info',
		'uses' => 'HomeController@patientDebugInfo'
	) );

	Route::get( 'search-patient', array(
		'as'   => 'search.patient',
		'uses' => 'HomeController@searchPatient'
	) );

	Route::get( 'patient/import', array(
		'as'   => 'patient.import',
		'uses' => 'HomeController@patientImport'
	) );
	Route::post( 'patient/enrol', array(
		'as'   => 'patient.enrol',
		'uses' => 'HomeController@patientEnrollment'
	) );

	Route::get( 'manage-report-schedule', array(
		'as'   => 'manage-schedule',
		'uses' => 'ReportSchedule@manageReportSchedule'
	) );

    Route::get( 'fitbit-steps', array(
        'as'   => 'fitbit-steps',
        'uses' => 'ReportController@sendMessages'
    ) );

	Route::get( 'support/tickets', array(
		'as'   => 'support.tickets',
		'uses' => 'SupportController@viewTickets'
	) );

    Route::any( 'cache-email', array(
        'as'   => 'cache-email',
        'uses' => 'CommonController@cacheEmail'
    ) );

	Route::group( array( 'as' => 'report.', 'prefix' => 'report', 'middleware' => [ 'cache-service' ] ), function () {
		Route::get( 'facility-reports/{facility_id?}', [
			'as'   => 'facility-reports',
			'uses' => 'ReportController@facilityReports'
		] );
		Route::get( 'users/active/{facility_id}/{days?}', [
			'as'   => 'facility.users.active',
			'uses' => 'ReportController@activeUsers'
		] );
		Route::get( 'users/entries/{facility_id}/{days?}', [
			'as'   => 'facility.users.entries',
			'uses' => 'ReportController@userEntries'
		] );
		Route::get( 'users/registration/{facility_id}/{days?}', [
			'as'   => 'facility.users.registration',
			'uses' => 'ReportController@userRegistrations'
		] );
		Route::get( 'misfit/steps/{facility_id}/{days?}', [
			'as'   => 'facility.misfit.steps',
			'uses' => 'ReportController@userMisfitSteps'
		] );
		Route::get( 'misfit/never-active/{facility_id}', [
			'as'   => 'facility.misfit.never.active',
			'uses' => 'ReportController@userMisfitNeverActive'
		] );
		Route::get( 'facility/messages/{facility_id}', [
			'as'   => 'facility.messages',
			'uses' => 'ReportController@facilityMessages'
		] );
		Route::get( 'video-calls/{facility_id}/{days?}', [
			'as'   => 'facility.video.calls',
			'uses' => 'ReportController@facilityVideoCalls'
		] );
		Route::get( 'users/lead-coach/{facility_id}', [
			'as'   => 'facility.users.leadCoach',
			'uses' => 'ReportController@facilityUsersLeadCoach'
		] );
		Route::get( 'facility/patient-preferences/{facility_id}', [
			'as'   => 'facility.patient-preferences',
			'uses' => 'ReportController@facilityPatientPreferences'
		] );
		Route::get( 'curriculum/activity/{facility_id}', [
			'as'   => 'facility.curriculum.activity',
			'uses' => 'ReportController@facilityCurriculumActivity'
		] );
		Route::get( 'facility/coach-patients/{facility_id}', [
			'as'   => 'coach.patients',
			'uses' => 'ReportController@facilityCoaches'
		] );
		Route::get( 'facility/weekly-participation/{facility_id}', [
			'as'   => 'weekly.participation',
			'uses' => 'ReportController@weeklyParticipation'
		] );
		Route::get( 'facility/sessions-completed/{facility_id}', [
			'as'   => 'sessions.completed',
			'uses' => 'ReportController@sessionsCompletedReport'
		] );
        Route::get( 'facility/self-register/{facility_id}', [
            'as'   => 'self.register',
            'uses' => 'ReportController@selfRegisterReport'
        ] );
        Route::get( 'facility/registration/{facility_id}', [
            'as'   => 'user.registration',
            'uses' => 'ReportController@usersRegistration'
        ] );
        Route::get( 'facility/import-patient', [
            'as'   => 'import.patient',
            'uses' => 'ReportController@importPatient'
        ] );
		Route::get( 'facility/engagement/{facility_id}', [
			'as'   => 'engagement',
			'uses' => 'ReportController@engagementReport'
		] );
		Route::get( 'facility/coach-engagement/{facility_id}', [
			'as'   => 'coach.engagement',
			'uses' => 'ReportController@coachEngagementReport'
		] );
		Route::get( 'facility/week-cohort/{facility_id}', [
			'as'   => 'week-cohort',
			'uses' => 'ReportController@weekCohortReport'
		] );

        Route::get( 'facility/fitbit-steps-mismatch', array(
            'as'   => 'fitbit-steps-mismatch',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReport'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-detail', array(
            'as'   => 'fitbit-steps-mismatch-detail',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetail'
        ) );

        Route::get( 'facility/fitbit-steps-mismatch-details', array(
            'as'   => 'fitbit-steps-mismatch-details',
            'uses' => 'v2\\FitbitActivitySteps@fitbitStepsMismatchReportDetails'
        ) );

        Route::get( 'facility/week-cohort', [
            'as'   => 'week-cohort-all-facility',
            'uses' => 'CommonController@weekCohortReport'
        ] );

		Route::get( 'facility/week-cohort/{facility_id}/group/{week?}/{coach?}', [
			'as'   => 'week-cohort-patients',
			'uses' => 'ReportController@weekCohortPatients'
		] );
		Route::get( 'facility/week-cohort/{facility_id}/group/{week}/detail/{log_week}', [
			'as'   => 'week-cohort-patients-log',
			'uses' => 'ReportController@weekCohortPatientsLog'
		] );
		Route::get( 'facility/patient-fitbit-activity/{facility_id}', [
			'as'   => 'patient.fitbit.activity',
			'uses' => 'ReportController@patientFitbitActivity'
		] );
		Route::get( 'facility/patient-fitbit-weight/{facility_id}/{days?}', [
			'as'   => 'patient.fitbit.weight',
			'uses' => 'ReportController@patientFitbitWeightReport'
		] );
		Route::get( 'facility/missing-patient-provider/{facility_id}', [
			'as'   => 'missing.patient-provider',
			'uses' => 'ReportController@missingPatientProviderMapping'
		] );

		Route::get( 'facility/member-coach-list/{facility_id}', [
			'as'   => 'facility.member-coach-list',
			'uses' => 'ReportController@memberCoachesListReport'
		] );

		Route::get( 'facility/shipping-addresses/{facility_id}', [
			'as'   => 'facility.shipping-addresses',
			'uses' => 'ReportController@facilityShippingAddresses'
		] );

		Route::get( 'provider/{provider_id}/patient-interaction/{week?}', [
			'as'   => 'coach.patient-interaction',
			'uses' => 'ReportController@coachPatientInteraction'
		] );


		Route::get( 'enrollment/{days?}', [
			'as'   => 'enrollment',
			'uses' => 'ReportController@enrollmentReport'
		] );
		Route::get( 'missing-fitbit-logs/activity/{days?}', [
			'as'   => 'missing-fitbit-log.activity',
			'uses' => 'ReportController@missingFitbitActivityLog'
		] );
		Route::get( 'missing-fitbit-logs/weight/{days?}', [
			'as'   => 'missing-fitbit-log.weight',
			'uses' => 'ReportController@missingFitbitWeightLog'
		] );

		Route::get( 'coach-weekly-participation', array(
			'as'   => 'coach-weekly-participation',
			'uses' => 'ProviderController@providerWeeklyParticipationReport'
		) );

		Route::get( 'feedback-messages', [
			'as'   => 'feedbackMessages',
			'uses' => 'ReportController@feedbackMessages'
		] );
		Route::get( 'patient-without-lead-coach', [
			'as'   => 'noLeadCoachOneonOne',
			'uses' => 'ReportController@patientWithoutLeadCoachOneOnOne'
		] );

		Route::get( 'messages/unreplied', [
			'as'   => 'unRepliedMessages',
			'uses' => 'ReportController@unRepliedMessages'

src/main/php/resources/views/includes/admin-layout.blade.php
@include('includes.header-styles')
@include('includes.header')
@include('includes.footer-scripts')

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <title>@yield('page-title','Home') | Heath Slate Admin </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Language" content="en">
    @yield('header-styles')
</head>
<body class="hold-transition skin-green sidebar-mini @yield('body-class')">
<!--[if lt IE 7]>
<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or
    <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->
<noscript>Javascript is required to view this page. Your browser does not support JavaScript or you have disabled JavaScript.</noscript>
<fieldset class="hidden parameters">
    <input type="hidden" name="alt_image_url" value="{{ asset('img/default-user-100x100.png') }}">
    <input type="hidden" name="report_datatable_row_per_page" value="{{ config('healthslate.report_datatable_row_per_page', 10) }}">
    <input type="hidden" name="table_row_per_page" value="{{ config( 'healthslate.table_row_per_page', 10 ) }}">
    <input type="hidden" name="default_js_date_time_format" value="{{ config( 'healthslate.default_js_date_time_format', 10 ) }}">
    <input type="hidden" name="internal_server_error" value="{{ trans( 'common.internal_server_error') }}">
</fieldset>
<div class="wrapper">

    @yield('header')

    @if(session('user')->userRole == 'ROLE_SUPER_ADMIN')
        @include('includes.sidebar')
        @yield('sidebar')
    @elseif(session('user')->userRole == 'ROLE_PROVIDER')
        @include('includes.sidebar-provider')
        @yield('sidebar-provider')
    @elseif(session('user')->userRole == 'ROLE_ADMIN')
        @include('includes.sidebar-admin')
        @yield('sidebar-admin')
    @elseif(session('user')->userRole == 'ROLE_FACILITY_ADMIN')
        @include('includes.sidebar-facility-admin')
        @yield('sidebar-facility-admin')
    @else
        @include('includes.sidebar-default')
        @yield('sidebar-default')
    @endif
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                @yield('page-title')
                <br/>
                <small id="page_description">{{ $page_description or null }}</small>

                <div class="pull-right action-btns" id="content-cache-btn">
                    <span class="label label-default small" title="Content is not current">Cached on <span class="time"></span></span>
                    <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#conf-clear-cache"><i class="glyphicon glyphicon-trash"></i> Clear</a>
                    <a href="#" class="btn btn-primary btn-sm bg-purple hide"><i class="glyphicon glyphicon-floppy-saved"></i> Enable Cache</a>
                </div>
            </h1>

            @yield('breadcrumb')

        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->
            @yield('content')

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <div class="modal" id="conf-clear-cache">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                {!! Form::open( ['method' => 'POST', 'id' => 'clear_cache', 'onsubmit' => 'return false;','role' => 'form', 'url' => route('ajax.cache-remove') ] ) !!}
                {!! Form::hidden('cache_key', null ) !!}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Confirm Action</h4>
                </div>
                <div class="modal-body">
                    <p>{{ trans('common.confirm_record_action',['action' => 'clear', 'element' => 'cached data']) }}</p>
                    <div class="message-bag"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                </div>
                {!! Form::close() !!}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            Heath Slate Admin
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; {{ date('Y') }}.</strong> All rights reserved.
    </footer>

    @yield('right-sidebar')
</div>
<!-- ./wrapper -->

<div class="loader" id="hs-loader">
    <div class="overlay">
        <i class="glyphicon glyphicon-refresh glyphicon-spin"></i>
    </div>
</div>
<div id="alerts-container"></div>
@yield('footer-scripts')

</body>
</html>

src/main/php/resources/views/includes/footer-scripts.blade.php
@section('footer-scripts')
    @parent
    <script src="{{ asset(elixir('js/application.js')) }}" ></script>
    @if (isset($js))
        @foreach ($js as $n)
            <script src="{{ asset(elixir('js/'.$n.'.js')) }}" ></script>
        @endforeach
    @endif
@stop

src/main/php/resources/views/includes/header-styles.blade.php
@section('header-styles')
    @parent
    <link href="{{ asset(elixir('css/application.css')) }}"  rel="stylesheet" type="text/css">
    @if (isset($css))
        @foreach ($css as $c)
            <link href="{{ asset(elixir('css/'.$c.'.css')) }}"  rel="stylesheet" type="text/css">
        @endforeach
    @endif
@stop

src/main/php/resources/views/includes/header.blade.php
@section('header')
<!-- Main Header -->
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('dashboard') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>HS</b> A</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>HealthSlate</b> Admin</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account Menu: style can be found in dropdown.less-->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset('img/default-user-100x100.png') }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ session('user')->firstName }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset('img/default-user-100x100.png') }}" class="img-circle" alt="User Image">
                            <p data-role="{{ session('user')->userRole }}">
                                {{ session('user')->firstName }} {{ session('user')->lastName }}
                                <small>{{ session('user')->userName }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left hide">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <!-- Right Sidebar - Not needed as of now
                <li>
                    <a href="#" data-toggle="control-sidebar"><span class="glyphicon glyphicon-cog"></span></a>
                </li>
                 -->
            </ul>
        </div>
    </nav>
</header>
@stop

src/main/php/resources/views/includes/right-sidebar.blade.php
@section('right-sidebar')
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading">Recent Activity</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript:void(0);">
                            <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                                <p>Will be 23 on April 24th</p>
                            </div>
                        </a>
                    </li>
                </ul><!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading">Tasks Progress</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript:void(0);">
                            <h4 class="control-sidebar-subheading">
                                Custom Template Design
                                <span class="label label-danger pull-right">70%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                            </div>
                        </a>
                    </li>
                </ul><!-- /.control-sidebar-menu -->

            </div><!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <h3 class="control-sidebar-heading">General Settings</h3>
                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            Report panel usage
                            <input type="checkbox" class="pull-right" checked>
                        </label>
                        <p>
                            Some information about this general settings option
                        </p>
                    </div><!-- /.form-group -->
                </form>
            </div><!-- /.tab-pane -->
        </div>
    </aside><!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
@stop

src/main/php/resources/views/includes/sidebar-default.blade.php
@section('sidebar-default')
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">HEADER</li>
                <!-- Optionally, you can add icons to the links -->
                <li @if(in_array(Request::route()->getName(), array('dashboard') )) class="active" @endif><a href="{{ route('dashboard') }}"><i class="glyphicon glyphicon-home"></i> <span>Dashboard</span></a></li>
            </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
@stop

src/main/php/resources/views/includes/sidebar.blade.php
@section('sidebar')
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form hide">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
                </div>
            </form>
            <!-- /.search form -->

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">HEADER</li>
                <!-- Optionally, you can add icons to the links -->
                <li @if(in_array(Request::route()->getName(), array('dashboard') )) class="active" @endif><a href="{{ route('dashboard') }}"><i class="glyphicon glyphicon-home"></i> <span>Dashboard</span></a></li>
                <li @if(in_array(Request::route()->getName(), array('facilities.list') )) class="active" @endif><a href="{{ route('facilities.list') }}"><i class="glyphicon glyphicon-list-alt"></i> <span>Facilities</span></a></li>

                <li @if(in_array(Request::route()->getName(), ['search.patient','patient.import'] )) class="active" @endif>
                    <a href="#"><i class="glyphicon glyphicon-user"></i>
                        <span>Patient</span>
                        <i class="glyphicon glyphicon-menu-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ route('search.patient') }}"> <i class="glyphicon glyphicon-search"></i> Search Patient</a></li>
                        <li><a href="{{ route('patient.import') }}"> <i class="glyphicon glyphicon-import"></i> Import Patient</a></li>
                    </ul>
                </li>

                <li class="treeview @if(request()->is('report/*')) active @endif">
                    <a href="#"><i class="glyphicon glyphicon-dashboard"></i>
                        <span>Reports</span>
                        <i class="glyphicon glyphicon-menu-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ route('report.facility-reports') }}">Facility Reports</a></li>
                        <li @if(in_array(Request::route()->getName(), array('report.week-cohort-all-facility') )) class="active" @endif><a href="{{ route('report.week-cohort-all-facility') }}">Week Cohort Report</a></li>
                        <li @if(in_array(Request::route()->getName(), array('report.import.patient') )) class="active" @endif><a href="{{ route('report.import.patient') }}">Patient Bulk Import Report</a></li>
                        <li><a href="{{ route('report.member-gone-inactive') }}">Member Gone Inactive</a></li>
                        <li><a href="{{ route('report.feedbackMessages') }}">Feedback Messages</a></li>
                        <li><a href="{{ route('report.noLeadCoachOneonOne') }}">Patient w/o Lead Coach<br/><small> One on One Session</small></a></li>
                        <li><a href="{{ route('report.unRepliedMessages') }}">Unreplied Messages</a></li>
                        <li><a href="{{ route('report.enrollment') }}">Enrollment Report</a></li>
                        <li><a href="{{ route('report.missing-fitbit-log.activity', ['days' => 1]) }}">Missing Fitbit Activity Logs</a></li>
                        <li><a href="{{ route('report.missing-fitbit-log.weight', ['days' => 1]) }}">Missing Fitbit Weight Logs</a></li>
                        <li><a href="{{ route('report.members-missing-facility-mapping') }}">Member Missing Facility Mapping</a></li>
                        <li @if(in_array(Request::route()->getName(), array('report.fitbit-steps-mismatch') )) class="active" @endif><a href="{{ route('report.fitbit-steps-mismatch' , ['days' => 30]) }}">Fitbit Steps Mismatch</a></li>
                        <li @if(in_array(Request::route()->getName(), array('cache-email') )) class="active" @endif><a href="{{ route('cache-email') }}">Cached Report Email Status</a></li>
                    </ul>
                </li>

                <li @if(in_array(Request::route()->getName(), array('manage-schedule') )) class="active" @endif><a href="{{ route('manage-schedule') }}"><i class="glyphicon glyphicon-time"></i> <span>Schedule Report</span></a></li>

                <li @if(in_array(Request::route()->getName(), ['support.tickets'] )) class="active" @endif>
                    <a href="#"><i class="glyphicon glyphicon-dashboard"></i>
                        <span>Support Service</span>
                        <i class="glyphicon glyphicon-menu-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ route('support.tickets') }}">Support Tickets</a></li>
                    </ul>
                </li>

                <li @if(in_array(Request::route()->getName(), array('fitbit-steps') )) class="active" @endif><a href="{{ route('fitbit-steps') }}"><i class="glyphicon glyphicon-info-sign"></i> <span>Fitbit Steps</span></a></li>

            </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
@stop